'use client'
import Navigation from '@/components/layout/navigation/Navigation'
import Footer from '@/components/layout/footer/Footer'
import '@/styles/index.scss'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, headerAnimation = true }) {
  return (
    <>
      <Navigation animation={headerAnimation} />
      <div className="content">{children}</div>
      <Footer />
    </>
  )
}
