'use client'
import '@/styles/index.scss'
import AOS from 'aos'
import 'aos/dist/aos.css'
import { useLang } from '@/locales'
import { useEffect } from 'react'
import { MantineProvider } from '@mantine/core'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const { lang } = useLang()

  useEffect(() => {
    if (process.browser) AOS.init()
  }, [])
  return (
    <html lang={lang}>
      <MantineProvider
        theme={{
          colorScheme: 'light',
        }}
      >
        <body>{children}</body>
      </MantineProvider>
    </html>
  )
}
